### ISSUE TITLE
gitignore for maven

### ISSUE THREAD

**Issue by bjtj** [develly/JPAProject#2]
Maven gitignore 를 적용해야 하겠습니다

https://github.com/github/gitignore/blob/master/Maven.gitignore

일반적으로 target 폴더는 빌드 산출물이기 때문에 version tracking 에 포함되지 않습니다

**Comment by develly** [comment]
**수정사항**
- maven gitignore 적용
- target 폴더 제거
- eclipse gitignore 적용

https://github.com/develly/JPAProject/commit/d505c9589a0c9b2af976a116b0102cc6e316304a
https://github.com/develly/JPAProject/commit/f055aaf6b81b17245980e344f94ceb5b7c3d15cd
https://github.com/develly/JPAProject/commit/e7eb8df7da78caa96d834dee15c97baf8a0dc3e8
